### ISSUE TITLE
Notice: Undefined index: ...

### ISSUE THREAD

**Issue by Erftralle** [Bakual/wetter#1]
...   21.03.18 **24:00** in ../mod_dwd_wettermodul/vertikal.php on line 34

I'm having this issue since updating to version 5.0.3.

**Comment by Bakual** [comment]
I think I know where that comes from. Since I round up the time now, the time value can be 24 now. But the data has only the 00:00. I need to catch that special case.

**Comment by Erftralle** [comment]
I see, thank you.
