### ISSUE TITLE
Wind Direction: MOD_DWD_WETTERMODUL_DIRECTION_16

### ISSUE THREAD

**Issue by Erftralle** [Bakual/wetter#2]
When determining the wind direction string with `ModDwdwetterHelper::getDirection($grad)` I think you should cast to int, otherwise the proove on the same type will fail:

```
public static function getDirection($grad)
{
  $index = (int) round($grad / 22.5);
  $index = ($index === 16) ? 0 : $index;

  return Text::_('MOD_DWD_WETTERMODUL_DIRECTION_' . $index);
}
```

**Comment by Bakual** [comment]
The `round` function returns a float, so the type safe check should work fine since `$index` contains a numeric value and not a string.
Did you have a specific issue or did this came up by reading the code?

**Comment by Erftralle** [comment]
> Did you have a specific issue ...

Yes, I had that specific issue. The module displayed exactly what the title of this issue says, namely
**Wind Direction: MOD_DWD_WETTERMODUL_DIRECTION_16**

 > ... or did this came up by reading the code?

I always try to check things as best as I can to prevent to waste others time. 

Since `gettype(16)` returns `integer ` the problem has been resolved for me by casting `$index `to integer.

The module showed
**Wind Direction: N**
afterwards.

**Comment by Bakual** [comment]
I'll see if I can reproduce this somehow. It shouldn't be necessary to cast to int because the return value from `round` already is a number, not a string. But maybe I miss something.
