### ISSUE TITLE
Notice: Undefined index: ...

### ISSUE THREAD

**Issue by Erftralle** [Bakual/wetter#3]
... 23.03.18 **23:00** in ..\mod_dwd_wettermodul\vertikal.php on line 34

I'm having this issue since updating to version 5.0.4.

**Comment by Bakual** [comment]
Can you give me the timestamp of that error so I see at which time it exactly happens?

**Comment by Erftralle** [comment]
It occurs daily between 23:00 and 23:59.

**Comment by Bakual** [comment]
Can you try if the current master solves it? You can download it and install from https://github.com/Bakual/wetter/archive/master.zip

**Comment by Erftralle** [comment]
Works fine.
Thank you very much and happy Easter.

**Comment by Bakual** [comment]
Fixed with https://github.com/Bakual/wetter/releases/tag/5.0.5
