### ISSUE TITLE
Issue with Icons

### ISSUE THREAD

**Issue by AssoMania** [Bakual/wetter#4]
Hello there,
I have an issue with the icon display on the module. 
It looks like that on the helper.php all the icons are not defined in the list (line 124 to 172).
There are more icons and not all of them are written in the code. 
As I don't know which case = which icon, can you help me with that please ?

The error in joomla :

`Notice: Undefined variable: icon in C:\wamp64\www\cockpit\modules\mod_dwd_wettermodul\helper.php on line 172`

Thank you

**Comment by Bakual** [comment]
Plesae try with the current developer version. You can download it at https://github.com/Bakual/wetter/archive/master.zip.
It should contain all possible cases according to the list from DWD.

**Comment by AssoMania** [comment]
Hello there, just came back around here because I had an update for the module on my website.
Didn't check in detail but I assume you fixed everything ? 
Thanks for the work, it's a nice module

**Comment by Bakual** [comment]
It should, but I can't say for certain as I don't know which version you used before.
Between 5.1.1 and 5.1.2 there should be no difference in regards to icons. But 5.1.1 should have fixed it.
