### ISSUE TITLE
Fehlermeldung beim installieren

### ISSUE THREAD

**Issue by ProggersWorld** [Bakual/wetter#6]
Hallo,

ich bekomme beim Installieren folgende Fehlermeldung:

Es ist ein Fehler aufgetreten.
0 Attempt to assign property "html" on null 

![grafik](https://user-images.githubusercontent.com/14744699/207134405-9de8f0d0-6d4b-4c35-a851-7981fd1f0197.png)

**Comment by Bakual** [comment]
@ProggersWorld Welche Version hast du denn versucht zu installieren? Die Version 6.0.0 funktioniert bei mir.

**Comment by ProggersWorld** [comment]
Hallo,

der Version 6.0.0 aus dem Joomla Webkatalog. 
Joomla V4.2.6
PHP 8

**Comment by Bakual** [comment]
Und wenn du die Datei von hier herunterlädst und dann so installierst?
https://github.com/Bakual/wetter/archive/refs/tags/6.0.0.zip

**Comment by ProggersWorld** [comment]
Ja, das hat funktioniert! Vielen Dank!

**Comment by Bakual** [comment]
Ich glaub ich habe den Fehler gefunden. Ich muss aber noch abwarten bis der Webinstaller die Daten vom JED übernimmt. Dann sehen wirs :-)

**Comment by Bakual** [comment]
Fixed mit https://github.com/Bakual/wetter/commit/df26d789ffbf98b222dcfb6cdf7d8f3bede7ded7
